### ISSUE TITLE
Change the scrollbar colour to match the theme

### ISSUE THREAD

**Issue by wifiextender** [duckduckgo/duckduckgo-styles#25]
Hello duckduckgo,

When a theme is changed, the scrollbar colours should inherit the newer one.

This is just an example from the **terminal** theme, notice the scrollbar colour:

![dark-bg-scrollbar](https://cloud.githubusercontent.com/assets/4725121/15884624/23dc74d8-2d52-11e6-94c7-2a1acecee4f5.png)

the variables [Less]

```less
//** `::-webkit-scrollbar`
@scroll-color-1: #252525;
@scroll-color-2: #4e4e4e;
@scroll-color-3: #222222;
@scroll-padding: 10px;
```

The scrollbar code [Less]

```less
//
// Scrollbar
// --------------------------------------------------

body::-webkit-scrollbar {
    width: @scroll-padding !important;
    height: @scroll-padding !important;
    background: @scroll-color-3 !important;
    border: 1px solid @scroll-color-1 !important;

    // the pseudo elems
    &-button {
        display: none !important;
    }

    &-thumb {
        border: 0 !important;
        box-shadow: none !important;
        min-height: 28px !important;
        background: @scroll-color-2 !important;
    }

    &-corner {
        background: @scroll-color-3 !important;
    }
}
```

Cheers
